/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wearl.feesmanagementsystem;


/**
 *
 * @author Saurabh
 */
public class Addfees extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Addfees.class.getName());

    
    
    /**
     * Creates new form SignUpPage
     */
    
    public void displayCashFirst()
    {
        GooglePay_Label.setVisible(false);
        PhonePe_Label.setVisible(false);
        Cheque_Label.setVisible(false);
        NEFT_Label.setVisible(false);
        bankname__label.setVisible(false);
        bank_name_field.setVisible(false);
        
    }
    
    public Addfees() {
        initComponents();
        displayCashFirst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UnameEnterError = new javax.swing.JLabel();
        PwdEnterError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        date_label = new javax.swing.JLabel();
        payment_mode_label = new javax.swing.JLabel();
        GooglePay_Label = new javax.swing.JLabel();
        PhonePe_Label = new javax.swing.JLabel();
        Cheque_Label = new javax.swing.JLabel();
        NEFT_Label = new javax.swing.JLabel();
        Gstin_label = new javax.swing.JLabel();
        Cash_Label = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        Receipt_no_label = new javax.swing.JLabel();
        Receipt_no_field = new javax.swing.JTextField();
        Mode_fields = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Courses_dropdown = new javax.swing.JComboBox<>();
        Remark_label = new javax.swing.JLabel();
        Total_in_words_field = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        received_month_field_1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        courses_label = new javax.swing.JLabel();
        sr_no_label = new javax.swing.JLabel();
        head__label = new javax.swing.JLabel();
        amount_label = new javax.swing.JLabel();
        received_month_field_2 = new javax.swing.JTextField();
        Rollno_field = new javax.swing.JTextField();
        Amount_field = new javax.swing.JTextField();
        rollno_label = new javax.swing.JLabel();
        first_amount = new javax.swing.JTextField();
        Cgst_label = new javax.swing.JLabel();
        Cgst_field = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Sgst_label = new javax.swing.JLabel();
        Sgst_field = new javax.swing.JTextField();
        Signature_label = new javax.swing.JLabel();
        Total_amount_field = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Total_label = new javax.swing.JLabel();
        Totalwords_label = new javax.swing.JLabel();
        Print_button = new javax.swing.JButton();
        Remark_field_panel = new javax.swing.JScrollPane();
        Remark_field = new javax.swing.JTextArea();
        bankname__label = new javax.swing.JLabel();
        payment_mode_dropdown = new javax.swing.JComboBox<>();
        bank_name_field = new javax.swing.JTextField();
        Home_button = new javax.swing.JButton();
        Search_button = new javax.swing.JButton();
        edit_course_button = new javax.swing.JButton();
        course_list_button = new javax.swing.JButton();
        all_record_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Fees - Saurabhh Fees Management System");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(700, 530));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setText("Add Fees Fields...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 320, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        UnameEnterError.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        UnameEnterError.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(UnameEnterError, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        PwdEnterError.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        PwdEnterError.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(PwdEnterError, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 430));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        date_label.setText("Date:");
        jPanel3.add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        payment_mode_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        payment_mode_label.setText("Mode of Payment:");
        jPanel3.add(payment_mode_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        GooglePay_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        GooglePay_Label.setText("GooglePay");
        jPanel3.add(GooglePay_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        PhonePe_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        PhonePe_Label.setText("PhonePe");
        jPanel3.add(PhonePe_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Cheque_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Cheque_Label.setText("Cheque");
        jPanel3.add(Cheque_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        NEFT_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NEFT_Label.setText("NEFT");
        jPanel3.add(NEFT_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Gstin_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Gstin_label.setText("GSTIN:  09IUW88J1Z7 ");
        jPanel3.add(Gstin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        Cash_Label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Cash_Label.setText("Cash");
        jPanel3.add(Cash_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        DateChooser.setBackground(new java.awt.Color(255, 255, 255));
        DateChooser.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jPanel3.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 30, 140, 20));

        Receipt_no_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Receipt_no_label.setText("Receipt No. ");
        jPanel3.add(Receipt_no_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Receipt_no_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Receipt_no_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receipt_no_fieldActionPerformed(evt);
            }
        });
        jPanel3.add(Receipt_no_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, -1));

        Mode_fields.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Mode_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode_fieldsActionPerformed(evt);
            }
        });
        jPanel3.add(Mode_fields, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("to");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 20, 20));

        Courses_dropdown.setBackground(new java.awt.Color(255, 204, 0));
        Courses_dropdown.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Courses_dropdown.setForeground(new java.awt.Color(255, 255, 255));
        Courses_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java Adv", "C++", "Dart", "Mern stack" }));
        jPanel4.add(Courses_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        Remark_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Remark_label.setText("Remark: ");
        jPanel4.add(Remark_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 20));

        Total_in_words_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Total_in_words_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_in_words_fieldActionPerformed(evt);
            }
        });
        jPanel4.add(Total_in_words_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Received from for the given month ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        received_month_field_1.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        received_month_field_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                received_month_field_1ActionPerformed(evt);
            }
        });
        jPanel4.add(received_month_field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 490, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 0, 51));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 267, 130, -1));

        courses_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        courses_label.setText("Course:");
        jPanel4.add(courses_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        sr_no_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        sr_no_label.setText("Sr No.");
        jPanel4.add(sr_no_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        head__label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        head__label.setText("Head");
        jPanel4.add(head__label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 30));

        amount_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        amount_label.setText("Amount");
        jPanel4.add(amount_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 30));

        received_month_field_2.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        received_month_field_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                received_month_field_2ActionPerformed(evt);
            }
        });
        jPanel4.add(received_month_field_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, -1));

        Rollno_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Rollno_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rollno_fieldActionPerformed(evt);
            }
        });
        jPanel4.add(Rollno_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 70, -1));

        Amount_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Amount_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amount_fieldActionPerformed(evt);
            }
        });
        jPanel4.add(Amount_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, -1));

        rollno_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        rollno_label.setText("Roll No: ");
        jPanel4.add(rollno_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        first_amount.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        first_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_amountActionPerformed(evt);
            }
        });
        jPanel4.add(first_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 80, -1));

        Cgst_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Cgst_label.setText("CGST 7%");
        jPanel4.add(Cgst_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, 20));

        Cgst_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Cgst_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cgst_fieldActionPerformed(evt);
            }
        });
        jPanel4.add(Cgst_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 0, 51));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 490, 20));

        Sgst_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Sgst_label.setText("SGST 6%");
        jPanel4.add(Sgst_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 20));

        Sgst_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Sgst_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sgst_fieldActionPerformed(evt);
            }
        });
        jPanel4.add(Sgst_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, -1));

        Signature_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Signature_label.setText("Signature");
        jPanel4.add(Signature_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, 20));

        Total_amount_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Total_amount_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_amount_fieldActionPerformed(evt);
            }
        });
        jPanel4.add(Total_amount_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 0, 51));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 490, 10));

        Total_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Total_label.setText("Total");
        jPanel4.add(Total_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 20));

        Totalwords_label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Totalwords_label.setText("Total in Words:");
        jPanel4.add(Totalwords_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, 20));

        Print_button.setBackground(new java.awt.Color(255, 0, 51));
        Print_button.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        Print_button.setForeground(new java.awt.Color(255, 255, 255));
        Print_button.setText("Print");
        Print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(Print_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        Remark_field.setColumns(20);
        Remark_field.setRows(5);
        Remark_field_panel.setViewportView(Remark_field);

        jPanel4.add(Remark_field_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 490, 330));

        bankname__label.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bankname__label.setText("Bank Name:");
        jPanel3.add(bankname__label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        payment_mode_dropdown.setBackground(new java.awt.Color(0, 153, 0));
        payment_mode_dropdown.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        payment_mode_dropdown.setForeground(new java.awt.Color(255, 255, 255));
        payment_mode_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GooglePay", "PhonePay", "Cheque", "NEFT", "Cash" }));
        payment_mode_dropdown.setSelectedIndex(4);
        payment_mode_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_mode_dropdownActionPerformed(evt);
            }
        });
        jPanel3.add(payment_mode_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        bank_name_field.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        bank_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_name_fieldActionPerformed(evt);
            }
        });
        jPanel3.add(bank_name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 490));

        Home_button.setBackground(new java.awt.Color(255, 51, 102));
        Home_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        Home_button.setForeground(new java.awt.Color(255, 255, 255));
        Home_button.setText("Home");
        Home_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_buttonMouseClicked(evt);
            }
        });
        Home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Home_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 30));

        Search_button.setBackground(new java.awt.Color(255, 51, 102));
        Search_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        Search_button.setForeground(new java.awt.Color(255, 255, 255));
        Search_button.setText("Search record");
        Search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 30));

        edit_course_button.setBackground(new java.awt.Color(255, 51, 102));
        edit_course_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        edit_course_button.setForeground(new java.awt.Color(255, 255, 255));
        edit_course_button.setText("Edit Course");
        edit_course_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_course_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(edit_course_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        course_list_button.setBackground(new java.awt.Color(255, 51, 102));
        course_list_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        course_list_button.setForeground(new java.awt.Color(255, 255, 255));
        course_list_button.setText("Course List");
        course_list_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_list_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(course_list_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 30));

        all_record_button.setBackground(new java.awt.Color(255, 51, 102));
        all_record_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        all_record_button.setForeground(new java.awt.Color(255, 255, 255));
        all_record_button.setText("View All Records");
        all_record_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_record_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(all_record_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 30));

        back_button.setBackground(new java.awt.Color(255, 51, 102));
        back_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 30));

        logout_button.setBackground(new java.awt.Color(255, 51, 102));
        logout_button.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        logout_button.setForeground(new java.awt.Color(255, 255, 255));
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 700, 490));

        setSize(new java.awt.Dimension(714, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_buttonActionPerformed

    private void Search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_buttonActionPerformed

    private void edit_course_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_course_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_course_buttonActionPerformed

    private void course_list_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_list_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_list_buttonActionPerformed

    private void all_record_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_record_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_all_record_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void Home_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_buttonMouseClicked

        Dashboard Db = new Dashboard();
        Db.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Home_buttonMouseClicked

    private void Total_in_words_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_in_words_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_in_words_fieldActionPerformed

    private void Receipt_no_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receipt_no_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Receipt_no_fieldActionPerformed

    private void Mode_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode_fieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mode_fieldsActionPerformed

    private void bank_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bank_name_fieldActionPerformed

    private void received_month_field_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_received_month_field_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_received_month_field_1ActionPerformed

    private void received_month_field_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_received_month_field_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_received_month_field_2ActionPerformed

    private void Rollno_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rollno_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rollno_fieldActionPerformed

    private void Amount_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amount_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amount_fieldActionPerformed

    private void first_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_amountActionPerformed

    private void Cgst_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cgst_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cgst_fieldActionPerformed

    private void Sgst_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sgst_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sgst_fieldActionPerformed

    private void Total_amount_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_amount_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_amount_fieldActionPerformed

    private void Print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Print_buttonActionPerformed

    private void payment_mode_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_mode_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_mode_dropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Addfees().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount_field;
    private javax.swing.JLabel Cash_Label;
    private javax.swing.JTextField Cgst_field;
    private javax.swing.JLabel Cgst_label;
    private javax.swing.JLabel Cheque_Label;
    private javax.swing.JComboBox<String> Courses_dropdown;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JLabel GooglePay_Label;
    private javax.swing.JLabel Gstin_label;
    private javax.swing.JButton Home_button;
    private javax.swing.JTextField Mode_fields;
    private javax.swing.JLabel NEFT_Label;
    private javax.swing.JLabel PhonePe_Label;
    private javax.swing.JButton Print_button;
    private javax.swing.JLabel PwdEnterError;
    private javax.swing.JTextField Receipt_no_field;
    private javax.swing.JLabel Receipt_no_label;
    private javax.swing.JTextArea Remark_field;
    private javax.swing.JScrollPane Remark_field_panel;
    private javax.swing.JLabel Remark_label;
    private javax.swing.JTextField Rollno_field;
    private javax.swing.JButton Search_button;
    private javax.swing.JTextField Sgst_field;
    private javax.swing.JLabel Sgst_label;
    private javax.swing.JLabel Signature_label;
    private javax.swing.JTextField Total_amount_field;
    private javax.swing.JTextField Total_in_words_field;
    private javax.swing.JLabel Total_label;
    private javax.swing.JLabel Totalwords_label;
    private javax.swing.JLabel UnameEnterError;
    private javax.swing.JButton all_record_button;
    private javax.swing.JLabel amount_label;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField bank_name_field;
    private javax.swing.JLabel bankname__label;
    private javax.swing.JButton course_list_button;
    private javax.swing.JLabel courses_label;
    private javax.swing.JLabel date_label;
    private javax.swing.JButton edit_course_button;
    private javax.swing.JTextField first_amount;
    private javax.swing.JLabel head__label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton logout_button;
    private javax.swing.JComboBox<String> payment_mode_dropdown;
    private javax.swing.JLabel payment_mode_label;
    private javax.swing.JTextField received_month_field_1;
    private javax.swing.JTextField received_month_field_2;
    private javax.swing.JLabel rollno_label;
    private javax.swing.JLabel sr_no_label;
    // End of variables declaration//GEN-END:variables
}
