/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wearl.feesmanagementsystem;

import java.awt.Color;
import java.sql.*;
import java.util.Date;
import java.text.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Saurabh
 */
public class SignUpPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage.class.getName());

    
    int id = 0;

    int getId() {
        ResultSet rs = null;
        try {
            // 1. Loading Driver   
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/wtfmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL";

            // 2. Establishing Connection
            Connection con = DriverManager.getConnection(url, "root", "Jaimaiki12345#");

            // Correct SELECT query to get max(id)
            String sql = "SELECT MAX(id) FROM signup";
            Statement st = con.createStatement();

            // executeQuery is correct here because SELECT returns a ResultSet
            rs = st.executeQuery(sql);

            // Extract value from ResultSet
            while (rs.next()) {
                id = rs.getInt(1);  // Column index starts from 1
                id++;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return id;
    }

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Contactnumber = new javax.swing.JTextField();
        Firstname = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        Cpassword = new javax.swing.JTextField();
        Dob = new com.toedter.calendar.JDateChooser();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        LablePasswordcheck = new javax.swing.JLabel();
        LableConfirmPasswordcheck = new javax.swing.JLabel();
        LableMobileNocheck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up Form - Saurabhh Fees Management System");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Contact Number ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Confirm password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("D.O.B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        Contactnumber.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Contactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactnumberActionPerformed(evt);
            }
        });
        Contactnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContactnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContactnumberKeyTyped(evt);
            }
        });
        getContentPane().add(Contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 160, -1));

        Firstname.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Firstname.setToolTipText("");
        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 160, -1));

        Lastname.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });
        getContentPane().add(Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, -1));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttxtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttxtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttxtPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttxtPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 160, -1));

        Username.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 160, -1));

        Cpassword.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 160, -1));
        getContentPane().add(Dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 160, -1));

        LoginButton.setBackground(new java.awt.Color(51, 102, 255));
        LoginButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, 30));

        SignUpButton.setBackground(new java.awt.Color(255, 102, 153));
        SignUpButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseExited(evt);
            }
        });
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 110, 30));

        ClearButton.setBackground(new java.awt.Color(0, 204, 0));
        ClearButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearButtonMouseExited(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 110, 30));

        LablePasswordcheck.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        LablePasswordcheck.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(LablePasswordcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, 20));

        LableConfirmPasswordcheck.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        LableConfirmPasswordcheck.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(LableConfirmPasswordcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, 20));

        LableMobileNocheck.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        LableMobileNocheck.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(LableMobileNocheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 20));

        setSize(new java.awt.Dimension(714, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactnumberActionPerformed

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void CpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpasswordActionPerformed

    private void txttxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttxtPasswordActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        LoginButton.setBackground(Color.BLACK);
        LoginButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        LoginButton.setBackground(Color.PINK);
        LoginButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_LoginButtonMouseExited

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        SignUpButton.setBackground(Color.BLACK);
        SignUpButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseExited
        SignUpButton.setBackground(Color.PINK);
        SignUpButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_SignUpButtonMouseExited

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        //Validation();
        if(Validation())
        {
            insertData();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Validation issue");
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
        ClearButton.setBackground(Color.BLACK);
        ClearButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_ClearButtonMouseClicked

    private void ClearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseExited
        ClearButton.setBackground(Color.PINK);
        ClearButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_ClearButtonMouseExited

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void txttxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttxtPasswordKeyPressed
        passwordCheck();
    }//GEN-LAST:event_txttxtPasswordKeyPressed

    private void txttxtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttxtPasswordKeyReleased
        passwordCheck();
    }//GEN-LAST:event_txttxtPasswordKeyReleased

    private void txttxtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttxtPasswordKeyTyped
        passwordCheck();
    }//GEN-LAST:event_txttxtPasswordKeyTyped

    private void ContactnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactnumberKeyPressed
        mobileNumberCheck();
    }//GEN-LAST:event_ContactnumberKeyPressed

    private void ContactnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactnumberKeyReleased
        mobileNumberCheck();
    }//GEN-LAST:event_ContactnumberKeyReleased

    private void ContactnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactnumberKeyTyped
        mobileNumberCheck();
    }//GEN-LAST:event_ContactnumberKeyTyped

    String Fname, Lname, Uname, Pwd, Cpwd, Cnumber;
    Date dob;

    void insertData() {

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/dd/MM");
        String Dobfinal = sdf.format(dob);

        try {
            //1. Loading Driver   
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/wtfmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL";
            //2. Establishing Statement or Connection
            Connection con = DriverManager.getConnection(url, "root", "Jaimaiki12345#");
            // Ek normal insert query chala rha hu jisse me jo signup table banaya hai abhi usne data ko insert kar saki
            String sql = "Insert into signup values(?, ? ,? ,? ,? ,?, ?)";
            //3. con ke pass ek prepareStatement nam ka function hota hai or ye preparedStatement naam ka data return krta hai  
            PreparedStatement st = con.prepareStatement(sql);

            st.setInt(1, getId());
            st.setString(2, Fname);
            st.setString(3, Lname);
            st.setString(4, Uname);
            st.setString(5, Pwd);
            st.setString(6, Dobfinal);
            st.setString(7, Cnumber);
            int i =st.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(this, "Record Inserted Successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Record Not Inserted Successfully");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    boolean Validation() {

        Fname = Firstname.getText();
        Lname = Lastname.getText();
        Uname = Username.getText();
        Pwd = txtPassword.getText();
        Cpwd = Cpassword.getText();
        Cnumber = Contactnumber.getText();
        dob = Dob.getDate();

        if (Fname.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter First Name.....");
            return false;
        }
        if (Lname.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Last Name.....");
            return false;
        }
        if (Uname.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Username.....");
            return false;
        }
        if (Pwd.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Password.....");
            return false;
        }
        if (Cpwd.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Confirm Password.....");
            return false;
        }

        try {
            if (dob == null) {
                JOptionPane.showMessageDialog(this, "Please Select Date Of Birth.....");
                return false;
            }
        } catch (NullPointerException e1) {
        }

        if (Cnumber.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Contact Number.....");
            return false;
        }
        return true;
    }

    void passwordCheck() {
        Pwd = txtPassword.getText();
        if (Pwd.length() >= 8) {
            LablePasswordcheck.setText("");
        } else {
            LablePasswordcheck.setText("Accept Only 8 Digit Pwd");
        }
    }

    void mobileNumberCheck() {
        Cnumber = Contactnumber.getText();

        if (Cnumber.length() == 10) {
            LableMobileNocheck.setText("");
        } else {
            LableMobileNocheck.setText("Enter 10 Digit No.");
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField Contactnumber;
    private javax.swing.JTextField Cpassword;
    private com.toedter.calendar.JDateChooser Dob;
    private javax.swing.JTextField Firstname;
    private javax.swing.JLabel LableConfirmPasswordcheck;
    private javax.swing.JLabel LableMobileNocheck;
    private javax.swing.JLabel LablePasswordcheck;
    private javax.swing.JTextField Lastname;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
